language: php

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - elasticsearch

before_install:
  # Disable XDebug speed up test execution.
  - phpenv config-rm xdebug.ini || return 0
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.6.deb && sudo dpkg -i --force-confnew elasticsearch-1.7.6.deb && sudo service elasticsearch restart

install:
  - make dependencies

script:
  - make test
  - make qa
  - make license
  - make changelog
